import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ModalProvider } from "@/components/modal-provider";
import ToasterProvide from "@/components/toaster-provider";
import CrispProvider from "@/components/CrispProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MindCraftAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <CrispProvider />
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <ModalProvider />
            <ToasterProvide />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
